'use client';

import { Lock, Trash } from '@phosphor-icons/react';
import type { InspectorKey, DeleteTarget } from '../types';

type Props = {
  keys: InspectorKey[];
  isLoading: boolean;
  isSuperadmin: boolean;
  onDelete: (target: DeleteTarget) => void;
};

export default function KeysTable({ keys, isLoading, isSuperadmin, onDelete }: Props) {
  return (
    <table className="w-full text-left border-collapse min-w-[900px]">
      <thead>
        <tr className="bg-canvas border-b border-line text-xs text-ink-muted">
          <th className="p-4 font-bold border-r border-line">Access Key</th>
          <th className="p-4 font-bold border-r border-line">Assigned Inspector</th>
          <th className="p-4 font-bold border-r border-line">Generated By</th>
          <th className="p-4 font-bold border-r border-line">Generated On</th>
          <th className="p-4 font-bold border-r border-line">Status</th>
          <th className="p-4 font-bold text-right">Actions</th>
        </tr>
      </thead>
      <tbody className="divide-y divide-line">
        {isLoading ? (
          <tr><td colSpan={6} className="p-12 text-center text-ink-muted text-xs">Loading provisioning database...</td></tr>
        ) : keys.length === 0 ? (
          <tr><td colSpan={6} className="p-12 text-center text-ink-muted text-xs">No access keys generated yet.</td></tr>
        ) : (
          keys.map((key) => (
            <tr key={key.id} className="hover:bg-sunken transition-colors duration-200">
              <td className="p-4 text-sm font-mono font-medium text-ink border-r border-line">{key.access_key}</td>
              <td className="p-4 text-sm font-bold text-ink border-r border-line">{key.assigned_to}</td>
              <td className="p-4 text-xs text-ink-muted border-r border-line">{key.created_by}</td>
              <td className="p-4 text-xs font-mono text-ink-muted border-r border-line">{new Date(key.created_at).toLocaleString()}</td>
              <td className="p-4 border-r border-line">
                {key.is_used ? (
                  <span className="inline-flex px-1.5 py-0.5 rounded-control text-xs font-bold bg-sunken text-ink-muted border border-line">
                    USED
                  </span>
                ) : (
                  <span className="inline-flex px-1.5 py-0.5 rounded-control text-xs font-bold bg-surface text-ink border border-line">
                    PENDING
                  </span>
                )}
              </td>
              <td className="p-4 text-right flex justify-end space-x-1">
                {isSuperadmin ? (
                  <button
                    onClick={() => onDelete({ id: key.id, name: `Access Key ${key.access_key}`, type: 'key' })}
                    className="p-1.5 text-ink-muted hover:text-danger-ink hover:bg-danger-bg rounded-control transition-colors duration-200"
                    title="Delete Key"
                  >
                    <Trash className="w-4 h-4" />
                  </button>
                ) : (
                  <button disabled className="p-1.5 text-shell-muted cursor-not-allowed"><Lock className="w-4 h-4" /></button>
                )}
              </td>
            </tr>
          ))
        )}
      </tbody>
    </table>
  );
}
